version: '3.4'

services:

  fedsite:
    container_name: fedsite-c
    build: ./image
    image: registry.cn-beijing.aliyuncs.com/leon-pu/longshanpanorama:latest
    ports:
      - "9891:80"